# Name : Sheikh Muhammad Asaj Ibtisam Nipun
ID:2215151017

Tasks:

1.Use numpy to create a 3×3 matrix of random integers between 1 and 50.  
2.Run the code twice </br>
With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.  
Without setting a seed, allowing random values to change each time

In [ ]:
import numpy as np

In [ ]:
np.random.seed(10)
matrix_with_seed = np.random.randint(1, 51, (3, 3))
print("Matrix with fixed seed:")
print(matrix_with_seed)

Matrix with fixed seed:
[[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [ ]:
matrix_without_seed = np.random.randint(1, 51, (3, 3))
print("\nMatrix without fixed seed:")
print(matrix_without_seed)


Matrix without fixed seed:
[[30 50  9]
 [10  1 43]
 [41 37 17]]


  3.Observe and explain the differences in outputs.  (in a different cell as text)

1.Using a Fixed Seed</br>
When a fixed seed is set, the random number remains the same every time the code runs. This is useful when the code needs to be executed multiple times while ensuring the matrix is generated consistently only once.

2.Without Seeding </br>
Without a seed, the code generates a new matrix with different random values each time it runs.







